QQuadra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('clubes/', include('clubes.urls')),
    path('admin/', admin.site.urls),
]

clubes/urls.py
from django.urls import path

from . import views

app_name = 'clubes'
urlpatterns = [    
    path('search/', views.search_post, name='search'),
    #path('', views.list_post, name='index'),
    #path('create/', views.create_post, name='create'),
    #path('update/<int:clube_id>/', views.update_post, name='update'),
    #path('delete/<int:clube_id>/', views.delete_post, name='delete'),
    #path('<int:clube_id>/', views.detail_post, name='detail'),
    path('', views.PostListView.as_view(), name='index'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:clube_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
    path('category/detail/<int:category_id>', views.list_category_clubes, name='categorydetail'),
    
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

clubes/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    descricao = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    clube = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255, default="Descrição da categoria")
    clubes = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

clubes/forms.py
from django.forms import ModelForm
from .models import Post, Comment



class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'descricao',
            'poster_url',
        ]
        labels = {
            'name': 'Nome',
            'descricao': 'Descrição',
            'poster_url': 'URL da Foto',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

clubes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .temp_data import clube_data
from .models import Post, Comment, Category
from django.views import generic
from .forms import PostForm, CommentForm



'''
def detail_post(request, clube_id):
    clube = get_object_or_404(Post, pk=clube_id)
    context = {'clube': clube}
    return render(request, 'clubes/detail.html', context)
'''
class PostDetailView(generic.DetailView):
    model = Post
    context_object_name = 'clube'
    template_name = 'clubes/detail.html'


'''
def list_post(request):
    clube_list = Post.objects.all()
    context = {'clube_list': clube_list}
    return render(request, 'clubes/index.html', context)
'''
class PostListView(generic.ListView):
    model = Post
    context_object_name = 'clube_list'
    template_name = 'clubes/index.html'



def search_post(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        clube_list = Post.objects.filter(name__icontains=search_term)
        context = {"clube_list": clube_list}
    return render(request, 'clubes/search.html', context)

'''
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            clube_name = form.cleaned_data['name']
            clube_descricao = form.cleaned_data['descricao']
            clube_poster_url = form.cleaned_data['poster_url']
            clube = Post(name=clube_name,
                         descricao=clube_descricao,
                         poster_url=clube_poster_url)
            clube.save()
            return HttpResponseRedirect(
                reverse('clubes:detail', args=(clube.id, )))
    else:
        form = PostForm()
        context = {'form': form}
        return render(request, 'clubes/create.html', context)
'''
class PostCreateView(generic.CreateView):
    context_object_name = 'clube'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "clubes/create.html"

    def get_success_url(self):
        return reverse('clubes:detail', kwargs={'pk': self.object.id})

'''
def update_post(request, clube_id):
    clube = get_object_or_404(Post, pk=clube_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            clube.name = form.cleaned_data['name']
            clube.descricao = form.cleaned_data['descricao']
            clube.poster_url = form.cleaned_data['poster_url']
            clube.save()
            return HttpResponseRedirect(
                reverse('clubes:detail', args=(clube.id, )))
    else:
        form = PostForm(
            initial={
                'name': clube.name,
                'descricao': clube.descricao,
                'poster_url': clube.poster_url
            })

    context = {'clube': clube, 'form': form}
    return render(request, 'clubes/update.html', context)
'''
class PostUpdateView(generic.UpdateView):
    context_object_name = 'clube'
    form_class = PostForm
    model = Post
    template_class = PostForm
    template_name = "clubes/update.html"

    def get_success_url(self):
        return reverse('clubes:detail', kwargs={'pk': self.object.id})


'''
def delete_post(request, clube_id):
    clube = get_object_or_404(Post, pk=clube_id)

    if request.method == "POST":
        clube.delete()
        return HttpResponseRedirect(reverse('clubes:index'))

    context = {'clube': clube}
    return render(request, 'clubes/delete.html', context)
'''

class PostDeleteView(generic.DeleteView):
    model = Post
    context_object_name = 'clube'
    template_name = 'clubes/delete.html'
    def get_success_url(self):
        return reverse('clubes:index')

def create_comment(request, clube_id):
    clube = get_object_or_404(Post, pk=clube_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            clube=clube)
            comment.save()
            return HttpResponseRedirect(
                reverse('clubes:detail', args=(clube_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'clube': clube}
    return render(request, 'clubes/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'clubes/category.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'clubes/create-category.html'
    fields = ['name', 'author', 'clubes']
    success_url = reverse_lazy('clubes:category')


def list_category_clubes(request, category_id):
    category = get_object_or_404(Category, pk= category_id)
    context = {'category': category}
    return render(request, 'clubes/categorydetail.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

clubes/templates/clubes/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Clubes</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'clubes:categorydetail' category.id %}">
                <h3>{{category.name}} </h3></a>
            
        </header>
        
    </article>
    {% endfor %}

    <a href="{% url 'clubes:create-category' %}"><button>Crie sua categoria</button></a>
</section>

{% endblock content %}

clubes/templates/clubes/categorydetail.html
{% extends 'base.html' %}
{% block title %}
{{ category.name }} 
{% endblock title %}

{% block content %}
<h2>{{ category.name | safe }} </h2>
<p>{{ category.descricao | safe }} </p>
<section class="lista-de-cards">
    <ul>
        {% for clube in category.clubes.all %}
            <div class="card">
                <a href="{% url 'clubes:detail' clube.id %}"><img src="{{ clube.poster_url }}"
                        alt="Foto do clube {{ clube.name}}"></a>
                <p>{{ clube.name | safe }}</p>
            </div>
        {% endfor %}
    </ul>
</section>

{% endblock content %}

clubes/templates/clubes/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar sobre {{ clube.name }} </h2>

<form action="{% url 'clubes:comment' clube.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentario</button>
</form>

<p><a href="{% url 'clubes:detail' clube.id %}">Voltar para a página do clube</a></p>
{% endblock content %}

clubes/templates/clubes/create-category.html
{% extends 'base.html' %}

{% block title %}
Criar Categoria
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'clubes:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

clubes/templates/clubes/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Clube</h2>
<form method="POST" action="{% url 'clubes:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

clubes/templates/clubes/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'clubes:delete' clube.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o clube "{{ clube.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

clubes/templates/clubes/detail.html
{% extends 'base.html' %}

{% block title %}
{{ clube.name }} 
{% endblock title %}

{% block content %}
<h2>Detalhes do {{ clube.name | safe }} </h2>

<section class="dados-de-clube">
    <img src="{{ clube.poster_url }}" alt="Poster do clube {{ clube.name}}">
    <ul>
        <li>Nome: {{ clube.name | safe }}</li>
        <li>Descrição: {{ clube.descricao | safe }} </li>
        <li>Data de postagem: {{ clube.date | date }} </li>
        {% if clube.category_set.all %}
            <li>Incluso nas categorias:
                <ul>
                    {% for category in clube.category_set.all %}
                    <li>
                        <a href="{% url 'clubes:categorydetail' category.id %}">{{ category }}</a>
                        
                    </li>
                    {% endfor %}
                </ul>  
                </li>
        {% endif %}
        <li><a href="{% url 'clubes:update' clube.id %}">Editar</a></li>
        <li><a href="{% url 'clubes:delete' clube.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentarios</h3>
    </header>
    <ul>
        {% if clube.comment_set.all %}
            {% for comment in clube.comment_set.all|dictsortreversed:"date" %}
                <figure>
                    <blockquote>
                        "{{ comment.text | safe }}"
                    </blockquote>
                    <figcaption>— {{ comment.author | safe }} <br> <b>Data de postagem: {{ comment.date | date }}</b>
                    <br>
                    <hr>
                </figure>

            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma comentario desse clube.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'clubes:comment' clube.pk %}"><button>Crie seu comentario</button></a>
</section>

{% endblock content %}

clubes/templates/clubes/index.html
{% extends 'base.html' %}


{% block content %}
<h2>Todos os Clubes</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'clubes:search' %}">Buscar Clubes</a></p>
    <p>Não encontrou o clube? <a href="{% url 'clubes:create' %}">Adicionar Novo Clube</a></p>
</section>

{% if clube_list %}
<section class="lista-de-cards">
    {% for clube in clube_list %}
    <article class="card">
        <a href="{% url 'clubes:detail' clube.id %}"><img src="{{ clube.poster_url }}"
            alt="Poster do clube {{ clube.name}}"></a>
        <p>{{ clube.name | safe }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum clube.</p>
{% endif %}

{% endblock content %}

clubes/templates/clubes/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Clube por Nome</h2>
<form action="{% url 'clubes:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if clube_list %}
<section class="lista-de-cards">
    {% for clube in clube_list %}
    <article class="card">
        <a href="{% url 'clubes:detail' clube.id %}"><img src="{{ clube.poster_url }}"
            alt="Poster do clube {{ clube.name}}"></a>
        <p>{{ clube.name }} </p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum clube para a busca.</p>
{% endif %}

{% endblock content %}

clubes/templates/clubes/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Clube {{ clube.name }} ({{ clube.descricao}})</h2>
<form method="POST" action="{% url 'clubes:update' clube.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>QQuadra</i></h1>
<p>A Página para Clubes</p>
<div class="row"> 
    <div class="column">
        <img  src="https://i.imgur.com/6SzVpUj.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/KrCTvQG.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/aFhJCip.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pHd22oY.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/f2ayYpE.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/ZeRWOmp.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/9fwRCMn.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/4tNs75x.jpg"
            style="width:100%">
    </div>
    <div class="column">
        <img  src="https://i.imgur.com/eYQ4Teo.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/sGsw4oH.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/fD6ETdm.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/MxXbgMD.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/12ANO1S.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/ilNSuAk.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/Sy9IkDx.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pNvmoDX.jpg"
            style="width:100%">
        </div>
    <div class="column">
        <img  src="https://i.imgur.com/5H6SoGb.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/IxKN6s9.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/pLFYhBZ.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/AQqKHmU.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/4tNs75x.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/Y9Qbx4p.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/Y9Qbx4p.jpg"
            style="width:100%">
        <img  src="https://i.imgur.com/qrvpHkI.jpg"
            style="width:100%">
    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | QQuadra
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'images/imagem_logo.png' %}" width="200" height="120"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'clubes:index' %}">Clubes</a></li>
                <li><a href="{% url 'clubes:category' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>